### ISSUE TITLE
Too many requests from this IP, please try again later.

### ISSUE THREAD

**Issue by MoistHoagie** [oppiliappan/lurker#7]
I just got this setup and an account created.  Was trying to subscribe to the subreddits and after just a minute or so I get this: "Too many requests from this IP, please try again later."  I assume this is something on the Reddit side throttling API requests, but is there anything else that could be done to help mitigate this issue?

**Comment by oppiliappan** [comment]
i have seen this a couple times, just restarting the server did the trick for me. not really sure what the issue is. i didn't really log a high rate of requests from my server either.

**Comment by disconn3ct** [comment]
https://github.com/oppiliappan/lurker/blob/57b747728127dd963f0a82eff3c82be508c915f8/src/index.js#L21 Since it doesn't handle x-forwarded-for, every query comes from the "same" address and it hits this hardcoded limit.
Maybe an option to enable trust proxy or to tune the rates? (Or disable it entirely.)
